# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
'''
Your Code
'''
import numpy as np
a = np.reshape(np.arange(1, 10), (3, 3))
print('list(a):{}'.format(list(a)))
print('tolist(a):{}'.format(a.tolist()))

list(a):[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
tolist(a):[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


若有多層的話, 以list()來轉換, 僅會轉換第一層的物件成串列, 而內部的元素依舊是Array, 若以tolist()轉換, 則可以將內部的元素全轉換成串列

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [3]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[2 7 3 2 6 8]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [9]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[7 8 6 9]
 [9 4 0 7]
 [5 2 1 6]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [5]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[7 0]
  [2 5]
  [0 9]]

 [[8 1]
  [5 9]
  [8 7]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 5, 1, 4, 7, 9]
[7, 5, 1, 4, 7, 9]


In [7]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[3, 8, 0, 3], [7, 4, 1, 2], [8, 3, 8, 5]]
[array([3, 8, 0, 3]), array([7, 4, 1, 2]), array([8, 3, 8, 5])]


In [8]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[3, 4], [7, 4], [8, 6]], [[8, 5], [0, 0], [6, 7]]]
[array([[3, 4],
       [7, 4],
       [8, 6]]), array([[8, 5],
       [0, 0],
       [6, 7]])]


In [11]:
def tolist(iterable):
    '''
    Your Code
    '''
    newlist=[]
    if type(iterable) != np.ndarray:
        return iterable
    else:
        for obj in iterable:
            newlist.append(tolist(obj))
        return newlist

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 5, 1, 4, 7, 9]
[[7, 8, 6, 9], [9, 4, 0, 7], [5, 2, 1, 6]]
[[[3, 4], [7, 4], [8, 6]], [[8, 5], [0, 0], [6, 7]]]


In [12]:
def tolist2(iterable):
    newlist = []
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist2(a))
print(tolist2(b))
print(tolist2(c))

[7, 5, 1, 4, 7, 9]
[[7, 8, 6, 9], [9, 4, 0, 7], [5, 2, 1, 6]]
[[[3, 4], [7, 4], [8, 6]], [[8, 5], [0, 0], [6, 7]]]
