# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
'''
Your Code
'''
import numpy as np
print(np.empty((2, 3)))

[[6.89798700e-307 2.00267682e-307 2.78150360e-307]
 [4.00541815e-307 2.78148492e-307 1.76128176e-312]]


In [2]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


1. np.empty()不會初始化陣列中元素數值, 僅會創造出指定大小的陣列, 將所有碰巧掛在內存中的值保留為值。這些值可以為零，也可以不為零，並不是指定的數值，由於他不需要初始化，所以其處理時間較為少
2. np.zeros()將陣列中元素均初始化為零，並依照指定的陣列大小初始化

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [3]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [13]:
# 參考解答

a = np.random.rand(2, 3)

'''
Your Code
'''
a.astype(np.int_)

array([[0, 0, 0],
       [0, 0, 0]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [18]:
m = 20
n = 40
a = np.random.rand(2, 3)
'''
Your Code
'''
print(a)

a_list = list(a)
a_new_list = []
for i in a_list:
    a_new_list.append((n-m)*i + m)
    
print(np.array(a_new_list))

[[0.09769878 0.64452708 0.8373521 ]
 [0.0947316  0.15413164 0.75905727]]
[[21.95397554 32.89054166 36.74704203]
 [21.89463196 23.08263278 35.18114545]]
