# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [2]:
import numpy as np

In [3]:
a = np.array([20,30,40,50])
b = np.array([1,2,3,4]) 
c = 1
d = np.array([1])
e = np.array([1,2])
print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

1. a + a = [40, 60, 80, 100]
2. a + b = [21, 32, 43, 54]
3. a + c = [21, 31, 41, 51]
4. a + d = [21, 31, 41, 51]
5. a + e = 無法運算, 由於形狀不同, 且也無法廣播

In [6]:
a_ = np.array([[[20],[30],[40],[50]]])
e_ = np.array([[[1],[2]]])
print(a_+e_)

ValueError: operands could not be broadcast together with shapes (1,4,1) (1,2,1) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [7]:
# 記得先 Import 正確的套件

import numpy as np


In [15]:
A = np.ones(3)*1
B = np.ones(3)*2

'''
Your Code
'''
print('由於array具有廣播與對其的特性, 對於每個元素可以不需要在迴圈的情況下計算:', (A+B)*(-A/2))
print('------------------------')
print('使用迴圈計算')
C = np.ones_like(A)
for i in range(A.shape[0]):
    C[i] = (A[i]+B[i])*(-A[i]/2)
print(C)

由於array具有廣播與對其的特性, 對於每個元素可以不需要在迴圈的情況下計算: [-1.5 -1.5 -1.5]
------------------------
使用迴圈計算
[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [34]:
A = np.ones((1,6))
B = np.ones((6,1))

'''
Your Code
'''
print('內積:\n', A@B) # 或者np.dot(A, B)
print('外積:\n', np.cross(A, B, axisa=0, axisb=0)) 


內積:
 [[6.]]


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```




### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


A = np.ones(3)*1
B = np.ones(3)*2

print((A + B) * (-A / 2))

### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


# 記得先 Import 正確的套件

import numpy as np


# 參考解答

A = np.ones((1,6))
B = np.ones((6,1))

print(A * B)
print(A @ B)



